Set Shell zsh
Output demo.gif
Set Width 1900
Set Height 800
Env AWS_ENDPOINT_URL "http://localhost:4566"
Env AWS_ACCESS_KEY_ID "test"
Env AWS_SECRET_ACCESS_KEY "test"
Env AWS_REGION "us-east-1"
Sleep 2s
Type "sacha"
Sleep 1.5s
Enter
Sleep 1.5s
Type "v "
Down
Sleep 500ms
Type " "
Sleep 500ms
Down
Type " "
Sleep 1s
Type "t"
Sleep 4s
Type "f"
Sleep 3s
Enter
Sleep 2.5s
Enter
Sleep 2.5s
Type "s"
Sleep 4s
Type "s"
Sleep 1s
Type "3"
Sleep 1.5s
Enter
Sleep 2s
Down
Sleep 1s
Enter
Sleep 2s
Enter
Sleep 500ms
Down
Sleep 500ms
Enter
Down
Sleep 1s
Enter
Sleep 500ms
Type " "
Sleep 1s
Type "d"
Sleep 3.5s
Ctrl+C
Sleep 1s

